# Generated by Django 3.2.3 on 2021-07-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likemodel',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='one like for one user in each post'),
        ),
    ]
